package fr.micklewright.smsvote.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import fr.micklewright.smsvote.database.Application;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table APPLICATION.
*/
public class ApplicationDao extends AbstractDao<Application, Long> {

    public static final String TABLENAME = "APPLICATION";

    /**
     * Properties of entity Application.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CandidateNumber = new Property(1, Integer.class, "candidateNumber", false, "CANDIDATE_NUMBER");
        public final static Property PostId = new Property(2, long.class, "postId", false, "POST_ID");
        public final static Property ApplicantId = new Property(3, long.class, "applicantId", false, "APPLICANT_ID");
    };

    private DaoSession daoSession;

    private Query<Application> post_ApplicationsQuery;
    private Query<Application> contact_ApplicationsQuery;

    public ApplicationDao(DaoConfig config) {
        super(config);
    }
    
    public ApplicationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'APPLICATION' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CANDIDATE_NUMBER' INTEGER," + // 1: candidateNumber
                "'POST_ID' INTEGER NOT NULL ," + // 2: postId
                "'APPLICANT_ID' INTEGER NOT NULL );"); // 3: applicantId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'APPLICATION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Application entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer candidateNumber = entity.getCandidateNumber();
        if (candidateNumber != null) {
            stmt.bindLong(2, candidateNumber);
        }
        stmt.bindLong(3, entity.getPostId());
        stmt.bindLong(4, entity.getApplicantId());
    }

    @Override
    protected void attachEntity(Application entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Application readEntity(Cursor cursor, int offset) {
        Application entity = new Application( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // candidateNumber
            cursor.getLong(offset + 2), // postId
            cursor.getLong(offset + 3) // applicantId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Application entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCandidateNumber(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setPostId(cursor.getLong(offset + 2));
        entity.setApplicantId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Application entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Application entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "applications" to-many relationship of Post. */
    public List<Application> _queryPost_Applications(long postId) {
        synchronized (this) {
            if (post_ApplicationsQuery == null) {
                QueryBuilder<Application> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PostId.eq(null));
                post_ApplicationsQuery = queryBuilder.build();
            }
        }
        Query<Application> query = post_ApplicationsQuery.forCurrentThread();
        query.setParameter(0, postId);
        return query.list();
    }

    /** Internal query to resolve the "applications" to-many relationship of Contact. */
    public List<Application> _queryContact_Applications(long applicantId) {
        synchronized (this) {
            if (contact_ApplicationsQuery == null) {
                QueryBuilder<Application> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ApplicantId.eq(null));
                contact_ApplicationsQuery = queryBuilder.build();
            }
        }
        Query<Application> query = contact_ApplicationsQuery.forCurrentThread();
        query.setParameter(0, applicantId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPostDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getContactDao().getAllColumns());
            builder.append(" FROM APPLICATION T");
            builder.append(" LEFT JOIN POST T0 ON T.'POST_ID'=T0.'_id'");
            builder.append(" LEFT JOIN CONTACT T1 ON T.'APPLICANT_ID'=T1.'NUMBER'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Application loadCurrentDeep(Cursor cursor, boolean lock) {
        Application entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Post post = loadCurrentOther(daoSession.getPostDao(), cursor, offset);
         if(post != null) {
            entity.setPost(post);
        }
        offset += daoSession.getPostDao().getAllColumns().length;

        Contact contact = loadCurrentOther(daoSession.getContactDao(), cursor, offset);
         if(contact != null) {
            entity.setContact(contact);
        }

        return entity;    
    }

    public Application loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Application> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Application> list = new ArrayList<Application>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Application> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Application> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
