package fr.micklewright.smsvote.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig electionDaoConfig;
    private final DaoConfig postDaoConfig;
    private final DaoConfig applicationDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig participationDaoConfig;
    private final DaoConfig voteDaoConfig;

    private final ElectionDao electionDao;
    private final PostDao postDao;
    private final ApplicationDao applicationDao;
    private final ContactDao contactDao;
    private final ParticipationDao participationDao;
    private final VoteDao voteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        electionDaoConfig = daoConfigMap.get(ElectionDao.class).clone();
        electionDaoConfig.initIdentityScope(type);

        postDaoConfig = daoConfigMap.get(PostDao.class).clone();
        postDaoConfig.initIdentityScope(type);

        applicationDaoConfig = daoConfigMap.get(ApplicationDao.class).clone();
        applicationDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        participationDaoConfig = daoConfigMap.get(ParticipationDao.class).clone();
        participationDaoConfig.initIdentityScope(type);

        voteDaoConfig = daoConfigMap.get(VoteDao.class).clone();
        voteDaoConfig.initIdentityScope(type);

        electionDao = new ElectionDao(electionDaoConfig, this);
        postDao = new PostDao(postDaoConfig, this);
        applicationDao = new ApplicationDao(applicationDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        participationDao = new ParticipationDao(participationDaoConfig, this);
        voteDao = new VoteDao(voteDaoConfig, this);

        registerDao(Election.class, electionDao);
        registerDao(Post.class, postDao);
        registerDao(Application.class, applicationDao);
        registerDao(Contact.class, contactDao);
        registerDao(Participation.class, participationDao);
        registerDao(Vote.class, voteDao);
    }
    
    public void clear() {
        electionDaoConfig.getIdentityScope().clear();
        postDaoConfig.getIdentityScope().clear();
        applicationDaoConfig.getIdentityScope().clear();
        contactDaoConfig.getIdentityScope().clear();
        participationDaoConfig.getIdentityScope().clear();
        voteDaoConfig.getIdentityScope().clear();
    }

    public ElectionDao getElectionDao() {
        return electionDao;
    }

    public PostDao getPostDao() {
        return postDao;
    }

    public ApplicationDao getApplicationDao() {
        return applicationDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public ParticipationDao getParticipationDao() {
        return participationDao;
    }

    public VoteDao getVoteDao() {
        return voteDao;
    }

}
