package fr.micklewright.smsvote.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PARTICIPATION.
*/
public class ParticipationDao extends AbstractDao<Participation, Void> {

    public static final String TABLENAME = "PARTICIPATION";

    /**
     * Properties of entity Participation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ContactNumber = new Property(0, long.class, "contactNumber", false, "CONTACT_NUMBER");
        public final static Property ElectionId = new Property(1, long.class, "electionId", false, "ELECTION_ID");
    };

    private DaoSession daoSession;

    private Query<Participation> contact_ParticipationsQuery;
    private Query<Participation> election_ParticipationsQuery;

    public ParticipationDao(DaoConfig config) {
        super(config);
    }
    
    public ParticipationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PARTICIPATION' (" + //
                "'CONTACT_NUMBER' INTEGER NOT NULL ," + // 0: contactNumber
                "'ELECTION_ID' INTEGER NOT NULL );"); // 1: electionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PARTICIPATION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Participation entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getContactNumber());
        stmt.bindLong(2, entity.getElectionId());
    }

    @Override
    protected void attachEntity(Participation entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public Participation readEntity(Cursor cursor, int offset) {
        Participation entity = new Participation( //
            cursor.getLong(offset + 0), // contactNumber
            cursor.getLong(offset + 1) // electionId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Participation entity, int offset) {
        entity.setContactNumber(cursor.getLong(offset + 0));
        entity.setElectionId(cursor.getLong(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(Participation entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(Participation entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "participations" to-many relationship of Contact. */
    public List<Participation> _queryContact_Participations(long contactNumber) {
        synchronized (this) {
            if (contact_ParticipationsQuery == null) {
                QueryBuilder<Participation> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ContactNumber.eq(null));
                contact_ParticipationsQuery = queryBuilder.build();
            }
        }
        Query<Participation> query = contact_ParticipationsQuery.forCurrentThread();
        query.setParameter(0, contactNumber);
        return query.list();
    }

    /** Internal query to resolve the "participations" to-many relationship of Election. */
    public List<Participation> _queryElection_Participations(long electionId) {
        synchronized (this) {
            if (election_ParticipationsQuery == null) {
                QueryBuilder<Participation> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ElectionId.eq(null));
                election_ParticipationsQuery = queryBuilder.build();
            }
        }
        Query<Participation> query = election_ParticipationsQuery.forCurrentThread();
        query.setParameter(0, electionId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getContactDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getElectionDao().getAllColumns());
            builder.append(" FROM PARTICIPATION T");
            builder.append(" LEFT JOIN CONTACT T0 ON T.'CONTACT_NUMBER'=T0.'NUMBER'");
            builder.append(" LEFT JOIN ELECTION T1 ON T.'ELECTION_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Participation loadCurrentDeep(Cursor cursor, boolean lock) {
        Participation entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Contact contact = loadCurrentOther(daoSession.getContactDao(), cursor, offset);
         if(contact != null) {
            entity.setContact(contact);
        }
        offset += daoSession.getContactDao().getAllColumns().length;

        Election election = loadCurrentOther(daoSession.getElectionDao(), cursor, offset);
         if(election != null) {
            entity.setElection(election);
        }

        return entity;    
    }

    public Participation loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Participation> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Participation> list = new ArrayList<Participation>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Participation> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Participation> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
