package fr.micklewright.smsvote.database;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VOTE.
 */
public class Vote {

    private long contactNumber;
    private long applicationId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient VoteDao myDao;

    private Contact contact;
    private Long contact__resolvedKey;

    private Application application;
    private Long application__resolvedKey;


    public Vote() {
    }

    public Vote(long contactNumber, long applicationId) {
        this.contactNumber = contactNumber;
        this.applicationId = applicationId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getVoteDao() : null;
    }

    public long getContactNumber() {
        return contactNumber;
    }

    public void setContactNumber(long contactNumber) {
        this.contactNumber = contactNumber;
    }

    public long getApplicationId() {
        return applicationId;
    }

    public void setApplicationId(long applicationId) {
        this.applicationId = applicationId;
    }

    /** To-one relationship, resolved on first access. */
    public Contact getContact() {
        long __key = this.contactNumber;
        if (contact__resolvedKey == null || !contact__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ContactDao targetDao = daoSession.getContactDao();
            Contact contactNew = targetDao.load(__key);
            synchronized (this) {
                contact = contactNew;
            	contact__resolvedKey = __key;
            }
        }
        return contact;
    }

    public void setContact(Contact contact) {
        if (contact == null) {
            throw new DaoException("To-one property 'contactNumber' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.contact = contact;
            contactNumber = contact.getNumber();
            contact__resolvedKey = contactNumber;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Application getApplication() {
        long __key = this.applicationId;
        if (application__resolvedKey == null || !application__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ApplicationDao targetDao = daoSession.getApplicationDao();
            Application applicationNew = targetDao.load(__key);
            synchronized (this) {
                application = applicationNew;
            	application__resolvedKey = __key;
            }
        }
        return application;
    }

    public void setApplication(Application application) {
        if (application == null) {
            throw new DaoException("To-one property 'applicationId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.application = application;
            applicationId = application.getId();
            application__resolvedKey = applicationId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
